Log4Qt: Log4Qt::Logger Class Reference
Log4Qt::Logger Class Reference
The class Logger provides logging services.
#include <logger.h>
Public Member Functions
bool additivity () const
QList< Appender * > appenders () const
Level level () const
LoggerRepository * loggerRepository () const
QString name () const
Logger * parentLogger () const
void setAdditivity (bool additivity)
virtual void setLevel (Level level)
void addAppender (Appender *pAppender)
Appender * appender (const QString &rName) const
void callAppenders (const LoggingEvent &rEvent) const
bool isAttached (Appender *pAppender) const
void removeAllAppenders ()
void removeAppender (Appender *pAppender)
void removeAppender (const QString &rName)
Level effectiveLevel () const
bool isDebugEnabled () const
bool isEnabledFor (Level level) const
bool isErrorEnabled () const
bool isFatalEnabled () const
bool isInfoEnabled () const
bool isTraceEnabled () const
bool isWarnEnabled () const
void debug (const QString &rMessage) const
void debug (const LogError &rLogError) const
void debug (const char *pMessage) const
void debug (const char *pMessage, const QString &rArg1) const
void debug (const char *pMessage, int arg1) const
void debug (const char *pMessage, const QString &rArg1, const QString &rArg2) const
void debug (const char *pMessage, const QString &rArg1, int arg2) const
void debug (const char *pMessage, int arg1, const QString &rArg2) const
void debug (const char *pMessage, int arg1, int arg2) const
void debug (const char *pMessage, const QString &rArg1, const QString &rArg2, const QString &rArg3) const
void debug (const char *pMessage, const QString &rArg1, const QString &rArg2, int arg3) const
void debug (const char *pMessage, const QString &rArg1, int arg2, const QString &rArg3) const
void debug (const char *pMessage, const QString &rArg1, int arg2, int arg3) const
void debug (const char *pMessage, int arg1, const QString &rArg2, const QString &rArg3) const
void debug (const char *pMessage, int arg1, const QString &rArg2, int arg3) const
void debug (const char *pMessage, int arg1, int arg2, const QString &rArg3) const
void debug (const char *pMessage, int arg1, int arg2, int arg3) const
void debug (const char *pMessage, const QVariant &rArg1, const QVariant &rArg2, const QVariant &rArg3) const
void error (const QString &rMessage) const
void error (const LogError &rLogError) const
void error (const char *pMessage) const
void error (const char *pMessage, const QString &rArg1) const
void error (const char *pMessage, int arg1) const
void error (const char *pMessage, const QString &rArg1, const QString &rArg2) const
void error (const char *pMessage, const QString &rArg1, int arg2) const
void error (const char *pMessage, int arg1, const QString &rArg2) const
void error (const char *pMessage, int arg1, int arg2) const
void error (const char *pMessage, const QString &rArg1, const QString &rArg2, const QString &rArg3) const
void error (const char *pMessage, const QString &rArg1, const QString &rArg2, int arg3) const
void error (const char *pMessage, const QString &rArg1, int arg2, const QString &rArg3) const
void error (const char *pMessage, const QString &rArg1, int arg2, int arg3) const
void error (const char *pMessage, int arg1, const QString &rArg2, const QString &rArg3) const
void error (const char *pMessage, int arg1, const QString &rArg2, int arg3) const
void error (const char *pMessage, int arg1, int arg2, const QString &rArg3) const
void error (const char *pMessage, int arg1, int arg2, int arg3) const
void error (const char *pMessage, const QVariant &rArg1, const QVariant &rArg2, const QVariant &rArg3) const
void fatal (const QString &rMessage) const
void fatal (const LogError &rLogError) const
void fatal (const char *pMessage) const
void fatal (const char *pMessage, const QString &rArg1) const
void fatal (const char *pMessage, int arg1) const
void fatal (const char *pMessage, const QString &rArg1, const QString &rArg2) const
void fatal (const char *pMessage, const QString &rArg1, int arg2) const
void fatal (const char *pMessage, int arg1, const QString &rArg2) const
void fatal (const char *pMessage, int arg1, int arg2) const
void fatal (const char *pMessage, const QString &rArg1, const QString &rArg2, const QString &rArg3) const
void fatal (const char *pMessage, const QString &rArg1, const QString &rArg2, int arg3) const
void fatal (const char *pMessage, const QString &rArg1, int arg2, const QString &rArg3) const
void fatal (const char *pMessage, const QString &rArg1, int arg2, int arg3) const
void fatal (const char *pMessage, int arg1, const QString &rArg2, const QString &rArg3) const
void fatal (const char *pMessage, int arg1, const QString &rArg2, int arg3) const
void fatal (const char *pMessage, int arg1, int arg2, const QString &rArg3) const
void fatal (const char *pMessage, int arg1, int arg2, int arg3) const
void fatal (const char *pMessage, const QVariant &rArg1, const QVariant &rArg2, const QVariant &rArg3) const
void info (const QString &rMessage) const
void info (const LogError &rLogError) const
void info (const char *pMessage) const
void info (const char *pMessage, const QString &rArg1) const
void info (const char *pMessage, int arg1) const
void info (const char *pMessage, const QString &rArg1, const QString &rArg2) const
void info (const char *pMessage, const QString &rArg1, int arg2) const
void info (const char *pMessage, int arg1, const QString &rArg2) const
void info (const char *pMessage, int arg1, int arg2) const
void info (const char *pMessage, const QString &rArg1, const QString &rArg2, const QString &rArg3) const
void info (const char *pMessage, const QString &rArg1, const QString &rArg2, int arg3) const
void info (const char *pMessage, const QString &rArg1, int arg2, const QString &rArg3) const
void info (const char *pMessage, const QString &rArg1, int arg2, int arg3) const
void info (const char *pMessage, int arg1, const QString &rArg2, const QString &rArg3) const
void info (const char *pMessage, int arg1, const QString &rArg2, int arg3) const
void info (const char *pMessage, int arg1, int arg2, const QString &rArg3) const
void info (const char *pMessage, int arg1, int arg2, int arg3) const
void info (const char *pMessage, const QVariant &rArg1, const QVariant &rArg2, const QVariant &rArg3) const
void log (Level level, const QString &rMessage) const
void log (Level level, const LogError &rLogError) const
void log (Level level, const char *pMessage) const
void log (Level level, const char *pMessage, const QString &rArg1) const
void log (Level level, const char *pMessage, int arg1) const
void log (Level level, const char *pMessage, const QString &rArg1, const QString &rArg2) const
void log (Level level, const char *pMessage, const QString &rArg1, int arg2) const
void log (Level level, const char *pMessage, int arg1, const QString &rArg2) const
void log (Level level, const char *pMessage, int arg1, int arg2) const
void log (Level level, const char *pMessage, const QString &rArg1, const QString &rArg2, const QString &rArg3) const
void log (Level level, const char *pMessage, const QString &rArg1, const QString &rArg2, int arg3) const
void log (Level level, const char *pMessage, const QString &rArg1, int arg2, const QString &rArg3) const
void log (Level level, const char *pMessage, const QString &rArg1, int arg2, int arg3) const
void log (Level level, const char *pMessage, int arg1, const QString &rArg2, const QString &rArg3) const
void log (Level level, const char *pMessage, int arg1, const QString &rArg2, int arg3) const
void log (Level level, const char *pMessage, int arg1, int arg2, const QString &rArg3) const
void log (Level level, const char *pMessage, int arg1, int arg2, int arg3) const
void log (Level level, const char *pMessage, const QVariant &rArg1, const QVariant &rArg2, const QVariant &rArg3) const
void trace (const QString &rMessage) const
void trace (const LogError &rLogError) const
void trace (const char *pMessage) const
void trace (const char *pMessage, const QString &rArg1) const
void trace (const char *pMessage, int arg1) const
void trace (const char *pMessage, const QString &rArg1, const QString &rArg2) const
void trace (const char *pMessage, const QString &rArg1, int arg2) const
void trace (const char *pMessage, int arg1, const QString &rArg2) const
void trace (const char *pMessage, int arg1, int arg2) const
void trace (const char *pMessage, const QString &rArg1, const QString &rArg2, const QString &rArg3) const
void trace (const char *pMessage, const QString &rArg1, const QString &rArg2, int arg3) const
void trace (const char *pMessage, const QString &rArg1, int arg2, const QString &rArg3) const
void trace (const char *pMessage, const QString &rArg1, int arg2, int arg3) const
void trace (const char *pMessage, int arg1, const QString &rArg2, const QString &rArg3) const
void trace (const char *pMessage, int arg1, const QString &rArg2, int arg3) const
void trace (const char *pMessage, int arg1, int arg2, const QString &rArg3) const
void trace (const char *pMessage, int arg1, int arg2, int arg3) const
void trace (const char *pMessage, const QVariant &rArg1, const QVariant &rArg2, const QVariant &rArg3) const
void warn (const QString &rMessage) const
void warn (const LogError &rLogError) const
void warn (const char *pMessage) const
void warn (const char *pMessage, const QString &rArg1) const
void warn (const char *pMessage, int arg1) const
void warn (const char *pMessage, const QString &rArg1, const QString &rArg2) const
void warn (const char *pMessage, const QString &rArg1, int arg2) const
void warn (const char *pMessage, int arg1, const QString &rArg2) const
void warn (const char *pMessage, int arg1, int arg2) const
void warn (const char *pMessage, const QString &rArg1, const QString &rArg2, const QString &rArg3) const
void warn (const char *pMessage, const QString &rArg1, const QString &rArg2, int arg3) const
void warn (const char *pMessage, const QString &rArg1, int arg2, const QString &rArg3) const
void warn (const char *pMessage, const QString &rArg1, int arg2, int arg3) const
void warn (const char *pMessage, int arg1, const QString &rArg2, const QString &rArg3) const
void warn (const char *pMessage, int arg1, const QString &rArg2, int arg3) const
void warn (const char *pMessage, int arg1, int arg2, const QString &rArg3) const
void warn (const char *pMessage, int arg1, int arg2, int arg3) const
void warn (const char *pMessage, const QVariant &rArg1, const QVariant &rArg2, const QVariant &rArg3) const
Static Public Member Functions
static Logger * logger (const QString &rName)
static Logger * logger (const char *pName)
static Logger * rootLogger ()
Protected Member Functions
Logger (LoggerRepository *pLoggerRepository, Level level, const QString &rName, Logger *pParent=0)
virtual ~Logger ()
virtual QDebug debug (QDebug &rDebug) const
void forcedLog (Level level, const QString &rMessage) const
Protected Attributes
QReadWriteLock mObjectGuard
Properties
bool additivity
Level level
LoggerRepository loggerRepository
QString name
Logger parentLogger
Friends
class Hierarchy
QDebug operator<< (QDebug debug, const Logger &rLogger)
Detailed Description
The class Logger provides logging services.
A pointer to a logger can be retrieved by calling Logger::logger() or LogManager::logger() with the class name as argument. Because a logger is never destroyed it is possible to store the pointer to the logger. This way the lookup of the pointer in the repository is only required on the first logging operation. The macros LOG4QT_DECLARE_STATIC_LOGGER and LOG4QT_DECLARE_QCLASS_LOGGER provide a thread-safe implementation to store the logger pointer.
Note:
All the functions declared in this class are thread-safe.
Constructor & Destructor Documentation
Log4Qt::Logger::Logger (LoggerRepository * pLoggerRepository, Level level, const QString & rName, Logger * pParent = 0) [protected]
virtual Log4Qt::Logger::~Logger () [protected, virtual]
Member Function Documentation
void Log4Qt::Logger::addAppender (Appender * pAppender)
bool Log4Qt::Logger::additivity () const
Appender* Log4Qt::Logger::appender (const QString & rName) const
QList<Appender*> Log4Qt::Logger::appenders () const
void Log4Qt::Logger::callAppenders (const LoggingEvent & rEvent) const
void Log4Qt::Logger::debug (const char * pMessage, int arg1, int arg2) const [inline]
References Log4Qt::Level::DEBUG_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::debug (const char * pMessage, const QString & rArg1, const QString & rArg2, const QString & rArg3) const [inline]
References Log4Qt::Level::DEBUG_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::debug (const char * pMessage, const QString & rArg1, const QString & rArg2, int arg3) const [inline]
References Log4Qt::Level::DEBUG_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::debug (const char * pMessage, const QString & rArg1, int arg2, const QString & rArg3) const [inline]
References Log4Qt::Level::DEBUG_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::debug (const char * pMessage, const QString & rArg1, int arg2, int arg3) const [inline]
References Log4Qt::Level::DEBUG_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::debug (const char * pMessage, int arg1, const QString & rArg2, const QString & rArg3) const [inline]
References Log4Qt::Level::DEBUG_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::debug (const char * pMessage, int arg1, const QString & rArg2, int arg3) const [inline]
References Log4Qt::Level::DEBUG_INT, forcedLog(), and isEnabledFor().
virtual QDebug Log4Qt::Logger::debug (QDebug & rDebug) const [protected, virtual]
Writes all object member variables to the given debug stream rDebug and returns the stream.
Logger(name:"Log4Qt" appenders:0 additivity:true Level("NULL") parentLogger: "root")
See also:
QDebug, operator<<(QDebug debug, const Appender &rAppender)
void Log4Qt::Logger::debug (const char * pMessage, int arg1, int arg2, const QString & rArg3) const [inline]
References Log4Qt::Level::DEBUG_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::debug (const char * pMessage, int arg1, int arg2, int arg3) const [inline]
References Log4Qt::Level::DEBUG_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::debug (const char * pMessage, const QVariant & rArg1, const QVariant & rArg2, const QVariant & rArg3) const [inline]
References Log4Qt::Level::DEBUG_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::debug (const QString & rMessage) const [inline]
References Log4Qt::Level::DEBUG_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::debug (const LogError & rLogError) const [inline]
References Log4Qt::Level::DEBUG_INT, forcedLog(), isEnabledFor(), and Log4Qt::LogError::toString().
void Log4Qt::Logger::debug (const char * pMessage) const [inline]
References Log4Qt::Level::DEBUG_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::debug (const char * pMessage, const QString & rArg1) const [inline]
References Log4Qt::Level::DEBUG_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::debug (const char * pMessage, int arg1) const [inline]
References Log4Qt::Level::DEBUG_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::debug (const char * pMessage, const QString & rArg1, const QString & rArg2) const [inline]
References Log4Qt::Level::DEBUG_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::debug (const char * pMessage, const QString & rArg1, int arg2) const [inline]
References Log4Qt::Level::DEBUG_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::debug (const char * pMessage, int arg1, const QString & rArg2) const [inline]
References Log4Qt::Level::DEBUG_INT, forcedLog(), and isEnabledFor().
Level Log4Qt::Logger::effectiveLevel () const
void Log4Qt::Logger::error (const QString & rMessage) const [inline]
References Log4Qt::Level::ERROR_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::error (const LogError & rLogError) const [inline]
References Log4Qt::Level::ERROR_INT, forcedLog(), isEnabledFor(), and Log4Qt::LogError::toString().
void Log4Qt::Logger::error (const char * pMessage) const [inline]
References Log4Qt::Level::ERROR_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::error (const char * pMessage, const QString & rArg1) const [inline]
References Log4Qt::Level::ERROR_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::error (const char * pMessage, int arg1) const [inline]
References Log4Qt::Level::ERROR_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::error (const char * pMessage, const QString & rArg1, const QString & rArg2) const [inline]
References Log4Qt::Level::ERROR_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::error (const char * pMessage, const QString & rArg1, int arg2) const [inline]
References Log4Qt::Level::ERROR_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::error (const char * pMessage, int arg1, const QString & rArg2) const [inline]
References Log4Qt::Level::ERROR_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::error (const char * pMessage, int arg1, int arg2) const [inline]
References Log4Qt::Level::ERROR_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::error (const char * pMessage, const QString & rArg1, const QString & rArg2, const QString & rArg3) const [inline]
References Log4Qt::Level::ERROR_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::error (const char * pMessage, const QString & rArg1, const QString & rArg2, int arg3) const [inline]
References Log4Qt::Level::ERROR_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::error (const char * pMessage, const QString & rArg1, int arg2, const QString & rArg3) const [inline]
References Log4Qt::Level::ERROR_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::error (const char * pMessage, const QString & rArg1, int arg2, int arg3) const [inline]
References Log4Qt::Level::ERROR_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::error (const char * pMessage, int arg1, const QString & rArg2, const QString & rArg3) const [inline]
References Log4Qt::Level::ERROR_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::error (const char * pMessage, int arg1, const QString & rArg2, int arg3) const [inline]
References Log4Qt::Level::ERROR_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::error (const char * pMessage, int arg1, int arg2, const QString & rArg3) const [inline]
References Log4Qt::Level::ERROR_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::error (const char * pMessage, int arg1, int arg2, int arg3) const [inline]
References Log4Qt::Level::ERROR_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::error (const char * pMessage, const QVariant & rArg1, const QVariant & rArg2, const QVariant & rArg3) const [inline]
References Log4Qt::Level::ERROR_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::fatal (const char * pMessage, int arg1) const [inline]
References Log4Qt::Level::FATAL_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::fatal (const char * pMessage, const QString & rArg1, const QString & rArg2) const [inline]
References Log4Qt::Level::FATAL_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::fatal (const char * pMessage, const QString & rArg1, int arg2) const [inline]
References Log4Qt::Level::FATAL_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::fatal (const char * pMessage, int arg1, const QString & rArg2) const [inline]
References Log4Qt::Level::FATAL_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::fatal (const char * pMessage, int arg1, int arg2) const [inline]
References Log4Qt::Level::FATAL_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::fatal (const char * pMessage, const QString & rArg1, const QString & rArg2, const QString & rArg3) const [inline]
References Log4Qt::Level::FATAL_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::fatal (const char * pMessage, const QString & rArg1, const QString & rArg2, int arg3) const [inline]
References Log4Qt::Level::FATAL_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::fatal (const char * pMessage, const QString & rArg1, int arg2, const QString & rArg3) const [inline]
References Log4Qt::Level::FATAL_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::fatal (const char * pMessage, const QString & rArg1, int arg2, int arg3) const [inline]
References Log4Qt::Level::FATAL_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::fatal (const char * pMessage, int arg1, const QString & rArg2, const QString & rArg3) const [inline]
References Log4Qt::Level::FATAL_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::fatal (const char * pMessage, int arg1, const QString & rArg2, int arg3) const [inline]
References Log4Qt::Level::FATAL_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::fatal (const char * pMessage, int arg1, int arg2, const QString & rArg3) const [inline]
References Log4Qt::Level::FATAL_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::fatal (const char * pMessage, int arg1, int arg2, int arg3) const [inline]
References Log4Qt::Level::FATAL_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::fatal (const char * pMessage, const QVariant & rArg1, const QVariant & rArg2, const QVariant & rArg3) const [inline]
References Log4Qt::Level::FATAL_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::fatal (const QString & rMessage) const [inline]
References Log4Qt::Level::FATAL_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::fatal (const LogError & rLogError) const [inline]
References Log4Qt::Level::FATAL_INT, forcedLog(), isEnabledFor(), and Log4Qt::LogError::toString().
void Log4Qt::Logger::fatal (const char * pMessage) const [inline]
References Log4Qt::Level::FATAL_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::fatal (const char * pMessage, const QString & rArg1) const [inline]
References Log4Qt::Level::FATAL_INT, forcedLog(), and isEnabledFor().
void Log4Qt::Logger::forcedLog (Level level, const QString & rMessage) const [protected]
Referenced by debug(), error(), fatal(), info(), log(), trace(), and warn().
void Log4Qt::Logger::info (const QString & rMessage) const [inline]
References forcedLog(), Log4Qt::Level::INFO_INT, and isEnabledFor().
void Log4Qt::Logger::info (const LogError & rLogError) const [inline]
References forcedLog(), Log4Qt::Level::INFO_INT, isEnabledFor(), and Log4Qt::LogError::toString().
void Log4Qt::Logger::info (const char * pMessage, int arg1, const QString & rArg2, const QString & rArg3) const [inline]
References forcedLog(), Log4Qt::Level::INFO_INT, and isEnabledFor().
void Log4Qt::Logger::info (const char * pMessage) const [inline]
References forcedLog(), Log4Qt::Level::INFO_INT, and isEnabledFor().
void Log4Qt::Logger::info (const char * pMessage, const QString & rArg1) const [inline]
References forcedLog(), Log4Qt::Level::INFO_INT, and isEnabledFor().
void Log4Qt::Logger::info (const char * pMessage, int arg1) const [inline]
References forcedLog(), Log4Qt::Level::INFO_INT, and isEnabledFor().
void Log4Qt::Logger::info (const char * pMessage, const QString & rArg1, const QString & rArg2) const [inline]
References forcedLog(), Log4Qt::Level::INFO_INT, and isEnabledFor().
void Log4Qt::Logger::info (const char * pMessage, const QString & rArg1, int arg2) const [inline]
References forcedLog(), Log4Qt::Level::INFO_INT, and isEnabledFor().
void Log4Qt::Logger::info (const char * pMessage, int arg1, const QString & rArg2) const [inline]
References forcedLog(), Log4Qt::Level::INFO_INT, and isEnabledFor().
void Log4Qt::Logger::info (const char * pMessage, int arg1, int arg2) const [inline]
References forcedLog(), Log4Qt::Level::INFO_INT, and isEnabledFor().
void Log4Qt::Logger::info (const char * pMessage, const QString & rArg1, const QString & rArg2, const QString & rArg3) const [inline]
References forcedLog(), Log4Qt::Level::INFO_INT, and isEnabledFor().
void Log4Qt::Logger::info (const char * pMessage, const QString & rArg1, const QString & rArg2, int arg3) const [inline]
References forcedLog(), Log4Qt::Level::INFO_INT, and isEnabledFor().
void Log4Qt::Logger::info (const char * pMessage, const QString & rArg1, int arg2, const QString & rArg3) const [inline]
References forcedLog(), Log4Qt::Level::INFO_INT, and isEnabledFor().
void Log4Qt::Logger::info (const char * pMessage, const QString & rArg1, int arg2, int arg3) const [inline]
References forcedLog(), Log4Qt::Level::INFO_INT, and isEnabledFor().
void Log4Qt::Logger::info (const char * pMessage, int arg1, const QString & rArg2, int arg3) const [inline]
References forcedLog(), Log4Qt::Level::INFO_INT, and isEnabledFor().
void Log4Qt::Logger::info (const char * pMessage, int arg1, int arg2, const QString & rArg3) const [inline]
References forcedLog(), Log4Qt::Level::INFO_INT, and isEnabledFor().
void Log4Qt::Logger::info (const char * pMessage, int arg1, int arg2, int arg3) const [inline]
References forcedLog(), Log4Qt::Level::INFO_INT, and isEnabledFor().
void Log4Qt::Logger::info (const char * pMessage, const QVariant & rArg1, const QVariant & rArg2, const QVariant & rArg3) const [inline]
References forcedLog(), Log4Qt::Level::INFO_INT, and isEnabledFor().
bool Log4Qt::Logger::isAttached (Appender * pAppender) const
bool Log4Qt::Logger::isDebugEnabled () const [inline]
References Log4Qt::Level::DEBUG_INT, and isEnabledFor().
bool Log4Qt::Logger::isEnabledFor (Level level) const
Checks if this logger is enabled for a given Level level. If the logger is enabled the function returns true. Otherwise it returns false.
A logger is enabled for a level, if the level is greater or equal then the repository threshold and greater and equal then the loggers effective level.
See also:
LoggerRepository::isDisabled(), effectiveLevel()
Referenced by debug(), error(), fatal(), info(), isDebugEnabled(), isErrorEnabled(), isFatalEnabled(), isInfoEnabled(), isTraceEnabled(), isWarnEnabled(), log(), trace(), and warn().
bool Log4Qt::Logger::isErrorEnabled () const [inline]
References Log4Qt::Level::ERROR_INT, and isEnabledFor().
bool Log4Qt::Logger::isFatalEnabled () const [inline]
References Log4Qt::Level::FATAL_INT, and isEnabledFor().
bool Log4Qt::Logger::isInfoEnabled () const [inline]
References Log4Qt::Level::INFO_INT, and isEnabledFor().
bool Log4Qt::Logger::isTraceEnabled () const [inline]
References isEnabledFor(), and Log4Qt::Level::TRACE_INT.
bool Log4Qt::Logger::isWarnEnabled () const [inline]
References isEnabledFor(), and Log4Qt::Level::WARN_INT.
Level Log4Qt::Logger::level () const
void Log4Qt::Logger::log (Level level, const char * pMessage, const QString & rArg1, int arg2, const QString & rArg3) const [inline]
References forcedLog(), and isEnabledFor().
void Log4Qt::Logger::log (Level level, const char * pMessage, int arg1, int arg2, const QString & rArg3) const [inline]
References forcedLog(), and isEnabledFor().
void Log4Qt::Logger::log (Level level, const char * pMessage, int arg1, const QString & rArg2) const [inline]
References forcedLog(), and isEnabledFor().
void Log4Qt::Logger::log (Level level, const char * pMessage, const QString & rArg1) const [inline]
References forcedLog(), and isEnabledFor().
void Log4Qt::Logger::log (Level level, const QString & rMessage) const [inline]
References forcedLog(), and isEnabledFor().
void Log4Qt::Logger::log (Level level, const LogError & rLogError) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::LogError::toString().
void Log4Qt::Logger::log (Level level, const char * pMessage) const [inline]
References forcedLog(), and isEnabledFor().
void Log4Qt::Logger::log (Level level, const char * pMessage, int arg1) const [inline]
References forcedLog(), and isEnabledFor().
void Log4Qt::Logger::log (Level level, const char * pMessage, const QString & rArg1, const QString & rArg2) const [inline]
References forcedLog(), and isEnabledFor().
void Log4Qt::Logger::log (Level level, const char * pMessage, const QString & rArg1, int arg2) const [inline]
References forcedLog(), and isEnabledFor().
void Log4Qt::Logger::log (Level level, const char * pMessage, int arg1, int arg2) const [inline]
References forcedLog(), and isEnabledFor().
void Log4Qt::Logger::log (Level level, const char * pMessage, int arg1, const QString & rArg2, int arg3) const [inline]
References forcedLog(), and isEnabledFor().
void Log4Qt::Logger::log (Level level, const char * pMessage, const QString & rArg1, const QString & rArg2, const QString & rArg3) const [inline]
References forcedLog(), and isEnabledFor().
void Log4Qt::Logger::log (Level level, const char * pMessage, const QString & rArg1, const QString & rArg2, int arg3) const [inline]
References forcedLog(), and isEnabledFor().
void Log4Qt::Logger::log (Level level, const char * pMessage, const QString & rArg1, int arg2, int arg3) const [inline]
References forcedLog(), and isEnabledFor().
void Log4Qt::Logger::log (Level level, const char * pMessage, int arg1, const QString & rArg2, const QString & rArg3) const [inline]
References forcedLog(), and isEnabledFor().
void Log4Qt::Logger::log (Level level, const char * pMessage, int arg1, int arg2, int arg3) const [inline]
References forcedLog(), and isEnabledFor().
void Log4Qt::Logger::log (Level level, const char * pMessage, const QVariant & rArg1, const QVariant & rArg2, const QVariant & rArg3) const [inline]
References forcedLog(), and isEnabledFor().
static Logger* Log4Qt::Logger::logger (const QString & rName) [static]
static Logger* Log4Qt::Logger::logger (const char * pName) [static]
LoggerRepository* Log4Qt::Logger::loggerRepository () const
QString Log4Qt::Logger::name () const
Logger* Log4Qt::Logger::parentLogger () const
void Log4Qt::Logger::removeAllAppenders ()
Removes all appenders that have been previously added from this Logger.
To allow configurators to collect events during the configuration process ListAppenders with the configuratorList property set, will not be removed.
See also:
LisAppender::setConfiguratorList()
void Log4Qt::Logger::removeAppender (Appender * pAppender)
void Log4Qt::Logger::removeAppender (const QString & rName)
static Logger* Log4Qt::Logger::rootLogger () [static]
void Log4Qt::Logger::setAdditivity (bool additivity) [inline]
virtual void Log4Qt::Logger::setLevel (Level level) [virtual]
void Log4Qt::Logger::trace (const char * pMessage, const QString & rArg1, const QString & rArg2) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::TRACE_INT.
void Log4Qt::Logger::trace (const char * pMessage, const QVariant & rArg1, const QVariant & rArg2, const QVariant & rArg3) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::TRACE_INT.
void Log4Qt::Logger::trace (const char * pMessage, int arg1, const QString & rArg2, int arg3) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::TRACE_INT.
void Log4Qt::Logger::trace (const LogError & rLogError) const [inline]
References forcedLog(), isEnabledFor(), Log4Qt::LogError::toString(), and Log4Qt::Level::TRACE_INT.
void Log4Qt::Logger::trace (const char * pMessage, int arg1, int arg2, int arg3) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::TRACE_INT.
void Log4Qt::Logger::trace (const char * pMessage, const QString & rArg1, int arg2, const QString & rArg3) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::TRACE_INT.
void Log4Qt::Logger::trace (const char * pMessage, int arg1, int arg2, const QString & rArg3) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::TRACE_INT.
void Log4Qt::Logger::trace (const char * pMessage, int arg1) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::TRACE_INT.
void Log4Qt::Logger::trace (const char * pMessage, const QString & rArg1, int arg2) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::TRACE_INT.
void Log4Qt::Logger::trace (const char * pMessage, int arg1, const QString & rArg2, const QString & rArg3) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::TRACE_INT.
void Log4Qt::Logger::trace (const QString & rMessage) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::TRACE_INT.
void Log4Qt::Logger::trace (const char * pMessage, const QString & rArg1, int arg2, int arg3) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::TRACE_INT.
void Log4Qt::Logger::trace (const char * pMessage, int arg1, const QString & rArg2) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::TRACE_INT.
void Log4Qt::Logger::trace (const char * pMessage, const QString & rArg1) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::TRACE_INT.
void Log4Qt::Logger::trace (const char * pMessage, int arg1, int arg2) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::TRACE_INT.
void Log4Qt::Logger::trace (const char * pMessage) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::TRACE_INT.
void Log4Qt::Logger::trace (const char * pMessage, const QString & rArg1, const QString & rArg2, const QString & rArg3) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::TRACE_INT.
void Log4Qt::Logger::trace (const char * pMessage, const QString & rArg1, const QString & rArg2, int arg3) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::TRACE_INT.
void Log4Qt::Logger::warn (const char * pMessage) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::WARN_INT.
void Log4Qt::Logger::warn (const char * pMessage, int arg1, int arg2, int arg3) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::WARN_INT.
void Log4Qt::Logger::warn (const char * pMessage, int arg1, int arg2, const QString & rArg3) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::WARN_INT.
void Log4Qt::Logger::warn (const char * pMessage, const QString & rArg1) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::WARN_INT.
void Log4Qt::Logger::warn (const QString & rMessage) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::WARN_INT.
void Log4Qt::Logger::warn (const char * pMessage, const QString & rArg1, int arg2) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::WARN_INT.
void Log4Qt::Logger::warn (const char * pMessage, int arg1, int arg2) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::WARN_INT.
void Log4Qt::Logger::warn (const char * pMessage, int arg1, const QString & rArg2, const QString & rArg3) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::WARN_INT.
void Log4Qt::Logger::warn (const char * pMessage, int arg1) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::WARN_INT.
void Log4Qt::Logger::warn (const char * pMessage, const QString & rArg1, const QString & rArg2) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::WARN_INT.
void Log4Qt::Logger::warn (const LogError & rLogError) const [inline]
References forcedLog(), isEnabledFor(), Log4Qt::LogError::toString(), and Log4Qt::Level::WARN_INT.
void Log4Qt::Logger::warn (const char * pMessage, int arg1, const QString & rArg2) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::WARN_INT.
void Log4Qt::Logger::warn (const char * pMessage, const QString & rArg1, const QString & rArg2, int arg3) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::WARN_INT.
void Log4Qt::Logger::warn (const char * pMessage, const QVariant & rArg1, const QVariant & rArg2, const QVariant & rArg3) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::WARN_INT.
void Log4Qt::Logger::warn (const char * pMessage, const QString & rArg1, const QString & rArg2, const QString & rArg3) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::WARN_INT.
void Log4Qt::Logger::warn (const char * pMessage, int arg1, const QString & rArg2, int arg3) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::WARN_INT.
void Log4Qt::Logger::warn (const char * pMessage, const QString & rArg1, int arg2, const QString & rArg3) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::WARN_INT.
void Log4Qt::Logger::warn (const char * pMessage, const QString & rArg1, int arg2, int arg3) const [inline]
References forcedLog(), isEnabledFor(), and Log4Qt::Level::WARN_INT.
Friends And Related Function Documentation
friend class Hierarchy [friend]
QDebug operator<< (QDebug debug, const Logger & rLogger) [friend]
Writes all object member variables to the given debug stream debug and returns the stream.
To handle subclassing the function uses the virtual member function debug(). This allows each class to generate its own output.
See also:
QDebug, debug()
Member Data Documentation
QReadWriteLock Log4Qt::Logger::mObjectGuard [mutable, protected]
Property Documentation
bool Log4Qt::Logger::additivity [inline, read, write]
The property holds, if the logger is additive.
The default is true for being additive.
See also:
additive(), setAdditive()
Level Log4Qt::Logger::level [inline, read, write]
The property holds the level used by the logger.
The default is Level::NULL_INT.
See also:
level(), setLevel()
LoggerRepository * Log4Qt::Logger::loggerRepository [inline, read]
The property holds the LoggerRepository of the logger.
See also:
loggerRepository()
QString Log4Qt::Logger::name [inline, read]
The property holds the name of the logger.
See also:
name()
Logger * Log4Qt::Logger::parentLogger [inline, read]
The property holds the parent logger of the logger.
See also:
parentLogger()
The documentation for this class was generated from the following file:
src/log4qt/logger.h